In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv('Data Sydney.csv')

In [4]:
np.sum(data.isnull())

Date              0
Location          0
MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          0
WindSpeed9am      0
WindSpeed3pm      0
Humidity9am       9
Humidity3pm      10
Pressure9am      10
Pressure3pm      26
Cloud9am         29
Cloud3pm         32
Temp9am          54
Temp3pm         618
RISK_MM         723
dtype: int64

In [5]:
data.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  1/2/2008   Sydney     19.5     22.4      15.6          6.2       0.0   
1  2/2/2008   Sydney     19.5     25.6       6.0          3.4       2.7   
2  3/2/2008   Sydney     21.6     24.5       6.6          2.4       0.1   
3  4/2/2008   Sydney     20.2     22.8      18.8          2.2       0.0   
4  5/2/2008   Sydney     19.7     25.7      77.4          0.0      11.0   

   WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
0          17.0          20.0         92.0         84.0       1017.6   
1           9.0          13.0         83.0         73.0       1017.9   
2          17.0           2.0         88.0         86.0       1016.7   
3          22.0          20.0         83.0         90.0       1014.2   
4           6.0          88.0         74.0       1008.3       1004.8   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RISK_MM  
0       1017.4       8.0       8.0     20.7     20.9      6.0  
1       1016.4       7.0       7.0     22.4     24.8      6.6  
2       1015.6       7.0       8.0     23.5     23.0     18.8  
3       1011.8       8.0       8.0     21.4     20.9     77.4  
4          8.0       8.0      22.5     25.5      1.6      NaN

In [6]:
data.describe()

MinTemp      MaxTemp     Rainfall  Evaporation     Sunshine  \
count  3344.000000  3344.000000  3344.000000  3344.000000  3344.000000   
mean     14.869587    22.977961     3.341597     5.197996     7.504844   
std       4.562860     4.545436     9.874956     2.864817     4.453951   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%      11.000000    19.600000     0.000000     3.200000     4.400000   
50%      14.900000    22.800000     0.000000     4.800000     8.400000   
75%      18.800000    26.000000     1.400000     7.000000    10.300000   
max      27.600000    45.800000   119.400000    37.000000    69.000000   

       WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  Pressure9am  \
count   3344.000000   3344.000000  3335.000000  3334.000000  3334.000000   
mean      15.726555     21.242853    73.311724    90.768476  1004.605655   
std       18.970364     21.343298    75.170637   184.473679   116.988059   
min        0.000000      0.000000     1.000000     2.000000     0.000000   
25%       11.000000     15.000000    58.000000    44.000000  1013.400000   
50%       15.000000     20.000000    69.000000    56.000000  1018.350000   
75%       20.000000     24.000000    80.000000    66.000000  1023.000000   
max     1009.900000   1021.300000  1027.200000  1037.000000  1039.000000   

       Pressure3pm     Cloud9am     Cloud3pm      Temp9am      Temp3pm  \
count  3318.000000  3315.000000  3312.000000  3290.000000  2726.000000   
mean    971.011223     6.595958     7.536564    15.566717    21.138665   
std     208.465361     6.148958     7.405595     8.386873     6.032295   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%    1010.500000     2.000000     2.000000    11.500000    18.300000   
50%    1015.900000     6.000000     6.000000    16.900000    21.200000   
75%    1020.600000     8.000000     8.000000    21.200000    24.500000   
max    1036.700000    34.900000    57.400000   109.400000   105.800000   

           RISK_MM  
count  2621.000000  
mean      3.036627  
std       9.063623  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max     119.400000

In [7]:
data['Humidity3pm']=data['Humidity3pm'].fillna((data['Humidity3pm'].median()))
np.sum(data.isnull())

Date              0
Location          0
MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          0
WindSpeed9am      0
WindSpeed3pm      0
Humidity9am       9
Humidity3pm       0
Pressure9am      10
Pressure3pm      26
Cloud9am         29
Cloud3pm         32
Temp9am          54
Temp3pm         618
RISK_MM         723
dtype: int64

In [8]:
data['Pressure9am']=data['Pressure9am'].fillna((data['Pressure9am'].median()))
data['Pressure3pm']=data['Pressure3pm'].fillna((data['Pressure3pm'].median()))
data['Humidity9am']=data['Humidity9am'].fillna((data['Humidity9am'].median()))
data['Cloud9am']=data['Cloud9am'].fillna((data['Cloud9am'].median()))
data['Cloud3pm']=data['Cloud3pm'].fillna((data['Cloud3pm'].median()))
data['Temp9am']=data['Temp9am'].fillna((data['Temp9am'].median()))
data['Temp3pm']=data['Temp3pm'].fillna((data['Temp3pm'].median()))
data['RISK_MM']=data['RISK_MM'].fillna((data['RISK_MM'].median()))
np.sum(data.isnull())

Date            0
Location        0
MinTemp         0
MaxTemp         0
Rainfall        0
Evaporation     0
Sunshine        0
WindSpeed9am    0
WindSpeed3pm    0
Humidity9am     0
Humidity3pm     0
Pressure9am     0
Pressure3pm     0
Cloud9am        0
Cloud3pm        0
Temp9am         0
Temp3pm         0
RISK_MM         0
dtype: int64

In [9]:
from scipy import stats
data1=data.drop('Date',1)
data2=data1.drop('Location',1)
z= np.abs(stats.zscore(data2._get_numeric_data()))
print(z)
data=data[(z<3).all(axis=1)]
print(data.shape)

[[1.0149566  0.12717085 1.24154843 ... 0.61444399 0.04590956 0.44583097]
 [1.0149566  0.5769373  0.26924683 ... 0.81878776 0.67027965 0.51972731]
 [1.47526306 0.33490013 0.33001568 ... 0.95101021 0.33973078 2.02228632]
 ...
 [1.19889827 1.1613297  0.33844167 ... 0.64767933 0.7070073  0.29313248]
 [1.04546279 0.80927562 0.33844167 ... 0.38323444 0.39482226 0.29313248]
 [1.59344667 0.80927562 0.33844167 ... 0.7438411  0.43154991 0.29313248]]
(2989, 18)


In [11]:
data.shape

(2989, 18)

In [21]:
x=data.iloc[0:2989,2:18]
x.shape

(2989, 16)

In [22]:
#normalisasi
from sklearn.preprocessing import normalize
xnorm=normalize(x,norm='l2') #default norm L2, other are L1 dan Max
xnorm=pd.DataFrame(xnorm)
xnorm.tail()

0         1    2         3         4         5         6   \
2984  0.005915  0.013482  0.0  0.001376  0.005365  0.015133  0.013757   
2985  0.006390  0.013193  0.0  0.001374  0.006322  0.013743  0.004810   
2986  0.006512  0.012261  0.0  0.001663  0.001870  0.010391  0.009005   
2987  0.007018  0.013410  0.0  0.000973  0.006462  0.011812  0.013201   
2988  0.005274  0.013394  0.0  0.002360  0.006524  0.009022  0.009022   

            7         8         9         10        11        12        13  \
2984  0.050213  0.035768  0.705659  0.705246  0.001376  0.001376  0.007222   
2985  0.053596  0.036418  0.706713  0.704033  0.001374  0.001374  0.007558   
2986  0.058882  0.038793  0.707134  0.703117  0.004156  0.004156  0.007066   
2987  0.038909  0.024318  0.706826  0.705297  0.003474  0.001390  0.008616   
2988  0.050662  0.022208  0.706910  0.704689  0.000694  0.000694  0.006524   

            14   15  
2984  0.012312  0.0  
2985  0.012849  0.0  
2986  0.011984  0.0  
2987  0.013201  0.0  
2988  0.013047  0.0

In [23]:
#feature selection (mencari skor)
from sklearn.feature_selection import SelectKBest, chi2, f_regression
Xx = x.iloc[0:2988,0:14]
y = x.iloc[0:2988,15]
selector = SelectKBest(f_regression, k=5).fit(Xx,y)
X_new = selector.transform(Xx)
scores = selector.scores_
scores

array([1.55663129e+01, 1.45833194e+01, 1.78650330e+02, 7.78475694e+00,
       3.77117235e+02, 1.73319609e-02, 1.16265528e+00, 1.70156778e+02,
       3.40766406e+02, 4.05944272e-01, 4.49797135e-01, 9.17272671e-01,
       2.22302056e+00, 4.85173038e+01])