In [50]:
import pandas as pd
import numpy as np

In [51]:
tugas=pd.read_csv('Auto Mobile Data Set.csv')

In [52]:
np.sum(tugas.isnull())

price                4
normalized-loses    41
horsepower           2
bore                 4
stroke               4
peak-rpm             2
engine-size          0
dtype: int64

In [53]:
tugas['price']=tugas['price'].fillna((tugas['price'].mean()))
tugas['normalized-loses']=tugas['normalized-loses'].fillna((tugas['normalized-loses'].mean()))
tugas['horsepower']=tugas['horsepower'].fillna((tugas['horsepower'].mean()))
tugas['bore']=tugas['bore'].fillna((tugas['bore'].mean()))
tugas['stroke']=tugas['stroke'].fillna((tugas['stroke'].mean()))
tugas['peak-rpm']=tugas['peak-rpm'].fillna((tugas['peak-rpm'].mean()))
np.sum(tugas.isnull())

price               0
normalized-loses    0
horsepower          0
bore                0
stroke              0
peak-rpm            0
engine-size         0
dtype: int64

In [55]:
tugas.to_csv('data1.csv', sep=',')

In [56]:
from scipy import stats

In [80]:
z= np.abs(stats.zscore(tugas._get_numeric_data()))
print(z)
tugas=tugas[(z<3).all(axis=1)]
print(tugas.shape)

[[0.51392808 0.06855545 0.50874254 ... 2.22884321 0.268742   0.51346383]
 [1.17998881 0.06855545 0.50874254 ... 2.22884321 0.268742   0.51346383]
 [1.17998881 0.06855545 1.96851138 ... 0.75976055 0.268742   1.38202726]
 ...
 [2.28491816 0.84160333 1.28954913 ... 1.51006509 0.84888475 2.21111054]
 [2.50324422 0.84160333 0.33900198 ... 0.49494756 0.7157927  1.10566617]
 [2.5376001  0.84160333 0.61058688 ... 0.45081312 0.6253594  0.94774555]]
(178, 7)


In [81]:
tugas.to_csv('data2.csv', sep=',')

In [82]:
tugas2=pd.read_csv('Auto Mobile Data Set.csv')
tugas2['price']=tugas2['price'].fillna((tugas2['price'].mean()))
tugas2['normalized-loses']=tugas2['normalized-loses'].fillna((tugas2['normalized-loses'].mean()))
tugas2['horsepower']=tugas2['horsepower'].fillna((tugas2['horsepower'].mean()))
tugas2['bore']=tugas2['bore'].fillna((tugas['bore'].mean()))
tugas2['stroke']=tugas2['stroke'].fillna((tugas2['stroke'].mean()))
tugas2['peak-rpm']=tugas2['peak-rpm'].fillna((tugas2['peak-rpm'].mean()))
np.sum(tugas2.isnull())

price               0
normalized-loses    0
horsepower          0
bore                0
stroke              0
peak-rpm            0
engine-size         0
dtype: int64

In [83]:
#normalization
from sklearn.preprocessing import normalize
tugas2norm=normalize(tugas2,norm='l2') #default norm L2, other are L1 dan Max
tugas2norm=pd.DataFrame(tugas2norm)
tugas2norm.tail()

0         1         2         3         4         5         6
200  0.952203  0.005370  0.006444  0.000214  0.000178  0.305248  0.007970
201  0.963324  0.004805  0.008093  0.000191  0.000159  0.268082  0.007132
202  0.968705  0.004283  0.006042  0.000161  0.000129  0.247981  0.007800
203  0.977898  0.004134  0.004613  0.000131  0.000148  0.208897  0.006310
204  0.972642  0.004084  0.004901  0.000163  0.000135  0.232144  0.006062

In [84]:
#3sigmoid
tugas2sigmoidal=(1-2.718281828**(-tugas2norm))/(1+2.718281828**(-tugas2norm))
tugas2sigmoidal=pd.DataFrame(tugas2sigmoidal)
tugas2sigmoidal.tail()

0         1         2         3         4         5         6
200  0.443116  0.002685  0.003222  0.000107  0.000089  0.151450  0.003985
201  0.447574  0.002403  0.004046  0.000096  0.000080  0.133244  0.003566
202  0.449723  0.002142  0.003021  0.000081  0.000065  0.123359  0.003900
203  0.453382  0.002067  0.002307  0.000065  0.000074  0.104070  0.003155
204  0.451291  0.002042  0.002450  0.000081  0.000068  0.115554  0.003031

In [85]:
tugas2sigmoidal.to_csv('data3.csv', sep=',')

In [86]:
#normalization data setelah hapus outlier
from sklearn.preprocessing import normalize
tugasnorm=normalize(tugas,norm='l2') #default norm L2, other are L1 dan Max
tugasnorm=pd.DataFrame(tugasnorm)
tugasnorm.tail()

0         1         2         3         4         5         6
173  0.952203  0.005370  0.006444  0.000214  0.000178  0.305248  0.007970
174  0.963324  0.004805  0.008093  0.000191  0.000159  0.268082  0.007132
175  0.968705  0.004283  0.006042  0.000161  0.000129  0.247981  0.007800
176  0.977898  0.004134  0.004613  0.000131  0.000148  0.208897  0.006310
177  0.972642  0.004084  0.004901  0.000163  0.000135  0.232144  0.006062

In [87]:
#3sigmoid transformasi setelah hapus outlier
tugassigmoidal=(1-2.718281828**(-tugasnorm))/(1+2.718281828**(-tugasnorm))
tugassigmoidal=pd.DataFrame(tugassigmoidal)
tugassigmoidal.tail()

0         1         2         3         4         5         6
173  0.443116  0.002685  0.003222  0.000107  0.000089  0.151450  0.003985
174  0.447574  0.002403  0.004046  0.000096  0.000080  0.133244  0.003566
175  0.449723  0.002142  0.003021  0.000081  0.000065  0.123359  0.003900
176  0.453382  0.002067  0.002307  0.000065  0.000074  0.104070  0.003155
177  0.451291  0.002042  0.002450  0.000081  0.000068  0.115554  0.003031

In [88]:
tugassigmoidal.to_csv('data4.csv', sep=',')