In [40]:
import pandas as pd
import numpy as np

In [41]:
tugas=pd.read_csv('datatugas.csv')

In [42]:
np.sum(tugas.isnull())

att1      12
att2      82
att3       5
att4     155
att5      21
att6      37
att7       0
att8      22
att9       0
att10      0
class      0
dtype: int64

In [43]:
tugas['att2']=tugas['att2'].fillna((tugas['att2'].mean()))
tugas['att4']=tugas['att4'].fillna((tugas['att4'].mean()))
tugas['att5']=tugas['att5'].fillna((tugas['att5'].mean()))
tugas['att6']=tugas['att6'].fillna((tugas['att6'].mean()))
tugas['att8']=tugas['att8'].fillna((tugas['att8'].mean()))
np.sum(tugas.isnull())

att1     12
att2      0
att3      5
att4      0
att5      0
att6      0
att7      0
att8      0
att9      0
att10     0
class     0
dtype: int64

In [44]:
from scipy.stats import mode

tugas['att1']=tugas['att1'].fillna(tugas['att1']).dropna().mode()[0]
tugas['att3']=tugas['att3'].fillna(tugas['att3']).dropna().mode()[0]
np.sum(data.isnull())

att1     0
att2     0
att3     0
att4     0
att5     0
att6     0
att7     0
att8     0
att9     0
att10    0
class    0
dtype: int64

In [45]:
from scipy import stats

In [46]:
tugas1=tugas.drop(['att1','att3','class'],1)
z= np.abs(stats.zscore(tugas1._get_numeric_data()))
print(z)
tugas=tugas[(z<3).all(axis=1)]
print(tugas.shape)

[[0.05232813 0.91916901 1.15647118 ... 1.51537248 0.49579284 1.14341756]
 [1.35137544 2.49289508 0.23775071 ... 0.76579366 0.07316842 1.2028276 ]
 [0.89168304 0.94461529 1.16723197 ... 1.06333639 0.07316842 0.13344684]
 ...
 [0.38478424 2.00998113 1.48842878 ... 0.79276868 1.12797201 0.07403679]
 [0.22266643 0.71531599 0.63609982 ... 0.59004726 0.87510034 0.52006363]
 [0.3191139  0.03929302 0.22698992 ... 0.78868156 1.08465509 1.35180422]]
(4990, 11)
